apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres
  namespace: tinker
spec:
  version: 9.6
  doNotPause: true
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 250Mi
